---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: get a fact action 
description: gets a fact from catfact and displayes the fact via curl and jq 
inputs:
  ename:
    description: name for this single param
    required: false
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.foofact.outputs.foofact.myfoofact }}
runs:
  using: composite
  steps:
    - id: get-a-fact
      name: create simple output
      uses: docker://finalspy/busybox-curl-jq
      shell: sh
      run: |
         res=`curl -ks  https://catfact.ninja/fact |jq .fact`
         echo "$res" 
         echo "we took a a param called ename which had a value of  ${{ inputs.ename }}"
    - id: foofact
      run: echo "myfoofact=echo this is my outout" >> $GITHUB_OUTPUT
      uses: docker://finalspy/busybox-curl-jq
      shell: sh
