---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: get a fact action 
description: gets a fact from catfact and displayes the fact via curl and jq
inputs:
  ename:
    description: name for this single param
    required: false
runs:
  using: composite
  steps:
    - id: getAFact
      name: Create simple output
      uses: docker://finalspy/busybox-curl-jq
      shell: sh
      run: |
        res=$(curl -s  https://catfact.ninja/fact |jq .fact)
        echo $res
        
