---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: get a fact action 
description: gets a fact from catfact and displayes the fact via curl and jq 
inputs:
  ename:
    description: name for this single param
    required: false

outputs:
    output1: "foo"
runs:
  using: composite
  steps:
    - id: get-a-fact
      name: create simple output
      uses: docker://finalspy/busybox-curl-jq
      shell: sh
      run: |
         res=`curl -ks  https://catfact.ninja/fact |jq .fact`
         echo "$res" > "$CLOUDBEES_OUTPUTS/fact"
         echo "we took a a param called ename which had a value of  ${{ inputs.ename }}"
        
